### PR TITLE
Simplify versioning for future releases

### PR DESCRIPTION
**Pull request by ryanjdew**
Use properties to simplify updating and adjusting versions for releases

### CODE REVIEW

**Comment by rjrudin** [comment]
Looks good to me!

**Comment by dmcassel** [comment]
Getting an error: 

> mvn test
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'version' contains an expression but should be a constant. @ line 26, column 14
[FATAL] Non-resolvable parent POM for org.apache.nifi:nifi-marklogic-bundle:${marklogicnar.version}: Failure to find org.apache.nifi:nifi-nar-bundles:pom:${nifi.version} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 20, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.apache.nifi:nifi-marklogic-bundle:${marklogicnar.version} (C:\Users\dcassel\git\nifi\nifi-nar-bundles\nifi-marklogic-bundle\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.apache.nifi:nifi-marklogic-bundle:${marklogicnar.version}: Failure to find org.apache.nifi:nifi-nar-bundles:pom:${nifi.version} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Ryan is checking whether the version of maven matters.

**Comment by ryanjdew** [comment]
Adjusted to be compatible with Maven 3.5+. The process for adjusting versions for releases will now be as follows:

1. `mvn versions:set -DnewVersion=<marklogic-nar-version>`
2. Edit the nifi-marklogic-bundle/pom.xml
- Set the parent version to <nifi-version>
- Set nifi.version property to the NiFi version and and marklogicnar.version property to the nar bundle version.

E.g.,  Steps for next release.
`mvn versions:set -DnewVersion=1.7.1`
nifi-marklogic-bundle/pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.nifi</groupId>
        <artifactId>nifi-nar-bundles</artifactId>
        <version>1.7.1</version>
    </parent>


    <version>1.7.1.1</version>

    <artifactId>nifi-marklogic-bundle</artifactId>
    <packaging>pom</packaging>

    <properties>
        <nifi.version>1.7.1</nifi.version>
        <marklogicnar.version>1.7.1.1</marklogicnar.version>
        <marklogicclientapi.version>4.1.1</marklogicclientapi.version>
        <mljavaclientutil.version>3.9.0</mljavaclientutil.version>
        <marklogicdatamovementcomponents.version>1.0</marklogicdatamovementcomponents.version>
    </properties>

    <modules>
        <module>nifi-marklogic-services-api</module>
        <module>nifi-marklogic-services-api-nar</module>
        <module>nifi-marklogic-services</module>
        <module>nifi-marklogic-processors</module>
        <module>nifi-marklogic-nar</module>
        <module>nifi-marklogic-services-nar</module>
    </modules>

</project>
```
`mvn clean test`

**Comment by dmcassel** [comment]
That worked

**Pull request merged**
